-- 论坛项目数据库初始化脚本
-- 基于 MyBatis Mapper 映射文件推断的表结构

-- 创建并使用新的数据库
CREATE DATABASE IF NOT EXISTS `db_forum` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE db_forum;

-- 1. 用户表
CREATE TABLE IF NOT EXISTS `t_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  `password` VARCHAR(128) NOT NULL COMMENT '密码',
  `nickname` VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  `phoneNum` VARCHAR(20) DEFAULT NULL COMMENT '电话号码',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `gender` TINYINT DEFAULT 0 COMMENT '性别: 0-未知, 1-男, 2-女',
  `salt` VARCHAR(32) DEFAULT NULL COMMENT '加密盐',
  `avatarUrl` VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
  `articleCount` INTEGER DEFAULT 0 COMMENT '发帖总数',
  `isAdmin` TINYINT DEFAULT 0 COMMENT '是否为管理员: 0-否, 1-是',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `state` TINYINT DEFAULT 0 COMMENT '状态: 0-正常, 1-禁用',
  `deleteState` TINYINT DEFAULT 0 COMMENT '逻辑删除: 0-未删除, 1-已删除',
  `createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 2. 板块表
CREATE TABLE IF NOT EXISTS `t_board` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NOT NULL COMMENT '板块名称',
  `articleCount` INTEGER DEFAULT 0 COMMENT '板块下帖子总数',
  `sort` INTEGER DEFAULT 0 COMMENT '排序',
  `state` TINYINT DEFAULT 0 COMMENT '状态',
  `deleteState` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  `createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='板块表';

-- 3. 帖子表
CREATE TABLE IF NOT EXISTS `t_article` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `boardId` BIGINT NOT NULL COMMENT '所属板块ID',
  `userId` BIGINT NOT NULL COMMENT '作者ID',
  `title` VARCHAR(255) NOT NULL COMMENT '帖子标题',
  `content` LONGTEXT NOT NULL COMMENT '帖子内容',
  `visitCount` INTEGER DEFAULT 0 COMMENT '访问量',
  `replyCount` INTEGER DEFAULT 0 COMMENT '回复量',
  `likeCount` INTEGER DEFAULT 0 COMMENT '点赞数',
  `state` TINYINT DEFAULT 0 COMMENT '状态',
  `deleteState` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  `createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_board_id` (`boardId`),
  KEY `idx_user_id` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='帖子表';

-- 4. 帖子回复表
CREATE TABLE IF NOT EXISTS `t_article_reply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `articleId` BIGINT NOT NULL COMMENT '帖子ID',
  `postUserId` BIGINT NOT NULL COMMENT '回复者ID',
  `replyId` BIGINT DEFAULT NULL COMMENT '被回复的评论ID',
  `replyUserId` BIGINT DEFAULT NULL COMMENT '被回复者ID',
  `content` VARCHAR(1000) NOT NULL COMMENT '回复内容',
  `likeCount` INTEGER DEFAULT 0 COMMENT '点赞数',
  `state` TINYINT DEFAULT 0 COMMENT '状态',
  `deleteState` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  `createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_article_id` (`articleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='帖子回复表';

-- 5. 消息表（站内信）
CREATE TABLE IF NOT EXISTS `t_message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `postUserId` BIGINT NOT NULL COMMENT '发送者ID',
  `receiveUserId` BIGINT NOT NULL COMMENT '接收者ID',
  `content` VARCHAR(1000) NOT NULL COMMENT '消息内容',
  `state` TINYINT DEFAULT 0 COMMENT '状态: 0-未读, 1-已读',
  `deleteState` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  `createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_receive_user_id` (`receiveUserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消息表';
